# Стаття блогу. Автор: Andrii Shestakov. Поля й формат — див. scripts/build_blog.py.

POST = {'key': 'skilky-koshtuie-sait',
 'path_uk': '/blog/skilky-koshtuie-sait-2026/',
 'path_pl': '/pl/blog/ile-kosztuje-strona-internetowa-2026/',
 'img': 'assets/why-2.webp',
 'title_uk': 'Скільки коштує сайт у 2026 році: ціни й терміни | SHSTKV Digital',
 'title_pl': 'Ile kosztuje strona internetowa w 2026? Ceny | SHSTKV Digital',
 'desc_uk': 'Скільки коштує сайт у 2026: від чого залежить ціна лендінгу, візитки й магазину, які витрати приховані і як читати комерційну пропозицію. Наші ціни — від €300.',
 'desc_pl': 'Ile kosztuje strona internetowa w 2026: od czego zależy cena wizytówki, strony firmowej i sklepu, jakie są ukryte koszty i jak czytać wycenę. Ceny od 300 €.',
 'h1_uk': 'Скільки коштує сайт у 2026 році',
 'h1_pl': 'Ile kosztuje strona internetowa w 2026 roku',
 'sub_uk': 'Від чого залежить ціна сайту, де ховаються додаткові витрати і скільки беремо ми.',
 'sub_pl': 'Od czego zależy cena strony, gdzie kryją się dodatkowe koszty i ile bierzemy my.',
 'topic_uk': 'Ціни',
 'topic_pl': 'Ceny',
 'minutes': 8,
 'answer_uk': 'Ціна сайту у 2026 році залежить від типу, кількості сторінок, функцій і того, хто робить. У нас лендінг коштує від €300 із запуском за 3 дні, багатосторінковий сайт — від €450 за '
              '15–25 робочих днів, інтернет-магазин — від €800 за 20–30 робочих днів. Окремо закладайте домен, хостинг, платні сервіси та підтримку.',
 'answer_pl': 'Cena strony w 2026 roku zależy od rodzaju, liczby podstron, funkcji i wykonawcy. U nas landing page kosztuje od 300 € ze startem w 3 dni, strona firmowa — od 450 € w 15–25 dni '
              'roboczych, a sklep internetowy — od 800 € w 20–30 dni roboczych. Osobno trzeba doliczyć domenę, hosting, płatne usługi i opiekę.',
 'sections': [{'h2_uk': 'Чому на одне питання — десять різних цін',
               'h2_pl': 'Dlaczego na jedno pytanie dostajesz dziesięć różnych cen',
               'blocks': [('p',
                           "Коли власник бізнесу розсилає запит «скільки коштує сайт» п'ятьом підрядникам, він отримує п'ять відповідей, які відрізняються в рази. Це не тому, що хтось обманює. "
                           'Просто кожен уявляє під словом «сайт» щось своє: хтось — одну сторінку на шаблоні, хтось — дизайн з нуля, тексти, аналітику й SEO.',
                           'Kiedy właściciel firmy wysyła pytanie „ile kosztuje strona internetowa” do pięciu wykonawców, dostaje pięć odpowiedzi, które różnią się kilkukrotnie. Nikt tu nie '
                           'kombinuje. Po prostu każdy rozumie pod hasłem „strona” coś innego: jeden — gotowy szablon z podmienionym logo, drugi — projekt od zera, teksty, analitykę i SEO.'),
                          ('p',
                           'За 12+ років у веб-розробці ми помітили закономірність: найдорожче обходяться не великі бюджети, а нечіткі. Тому спершу розберемося, з чого складається ціна, а вже потім '
                           '— у цифри.',
                           'Przez ponad 12 lat w branży zauważyliśmy prostą zależność: najdrożej wychodzą nie duże budżety, tylko niejasne. Dlatego najpierw rozłóżmy cenę na części, a dopiero potem '
                           'przejdźmy do liczb.')]},
              {'h2_uk': 'Від чого залежить ціна створення сайту',
               'h2_pl': 'Od czego zależy cena strony www',
               'blocks': [('p',
                           'Головний чинник — тип сайту. Далі на ціну впливають обсяг контенту, складність функцій і те, скільки роботи бере на себе підрядник, а скільки залишається вам.',
                           'Najważniejszy jest rodzaj strony. Dalej na cenę wpływają ilość treści, złożoność funkcji i to, ile pracy bierze na siebie wykonawca, a ile zostaje po Twojej stronie.'),
                          ('ul',
                           [('<strong>Тип і кількість сторінок.</strong> Лендінг на одну пропозицію, візитка на 1–5 сторінок, корпоративний сайт із розділами послуг чи магазин із каталогом — це '
                             'різні обсяги роботи.',
                             '<strong>Rodzaj i liczba podstron.</strong> Landing pod jedną ofertę, wizytówka na 1–5 podstron, strona firmowa z podstronami usług czy sklep z katalogiem — to zupełnie '
                             'inny zakres pracy.'),
                            ('<strong>Дизайн.</strong> Готовий шаблон дешевший, індивідуальний дизайн під ваш бренд — дорожчий, але не схожий на сотні інших сайтів.',
                             '<strong>Projekt graficzny.</strong> Gotowy szablon jest tańszy, indywidualny projekt pod Twoją markę — droższy, ale nie wygląda jak setki innych stron.'),
                            ('<strong>Функції.</strong> Калькулятор, онлайн-оплата, інтеграція зі службою доставки, кабінет клієнта — кожна додає дні розробки.',
                             '<strong>Funkcje.</strong> Kalkulator, płatności online (BLIK, karty), integracja z InPost, konto klienta — każda z nich to dodatkowe dni pracy.'),
                            ('<strong>Мови.</strong> Кожна мовна версія — це переклад, окремі мета-теги й налаштування hreflang.',
                             '<strong>Wersje językowe.</strong> Każdy język to tłumaczenie, osobne meta tagi i konfiguracja hreflang.'),
                            ('<strong>Контент.</strong> Якщо тексти й фото готові, робота йде швидше. Якщо їх треба писати й знімати — це окремий пункт бюджету.',
                             '<strong>Treści.</strong> Jeśli teksty i zdjęcia są gotowe, praca idzie szybciej. Jeśli teksty trzeba napisać, a zdjęcia zrobić — to osobna pozycja w budżecie.'),
                            ('<strong>Редагування.</strong> Адмін-панель, де ви самі міняєте ціни й фото, коштує дорожче за статичний сайт, зате економить на правках потім.',
                             '<strong>Edycja.</strong> Panel, w którym sam zmieniasz ceny i zdjęcia, kosztuje więcej niż strona statyczna, ale potem oszczędzasz na drobnych poprawkach.')])]},
              {'h2_uk': 'Ціни за типами сайтів: наша таблиця',
               'h2_pl': 'Ceny według rodzaju strony: nasz cennik',
               'blocks': [('p',
                           'Нижче — наші стартові ціни на бюджетні варіанти. Усе, що виходить за їхні межі, ми рахуємо після брифу, а оцінку надсилаємо протягом 24 годин. Повний перелік — на '
                           'сторінці <a href="prices">цін на створення сайтів</a>.',
                           'Poniżej nasze ceny startowe dla budżetowych wariantów. Wszystko, co wykracza poza ich zakres, wyceniamy po briefie, a odpowiedź wysyłamy w ciągu 24 godzin. Pełna lista jest w '
                           'naszym <a href="prices">cenniku stron internetowych</a>. Ceny są końcowe — nie doliczamy VAT, bo korzystamy ze zwolnienia z VAT.'),
                          ('table',
                           [('Тип сайту', 'Rodzaj strony'), ('Типовий обсяг', 'Typowy zakres'), ('Ціна', 'Cena'), ('Термін', 'Termin')],
                           [[('Лендінг «Старт»', 'Landing „Start”'),
                             ('Одна сторінка під одну пропозицію, форма заявки в Telegram', 'Jedna strona pod jedną ofertę, formularz z powiadomieniami na Telegramie'),
                             ('від €300', 'od 300 €'),
                             ('3 дні', '3 dni')],
                            [('Лендінг «Про»', 'Landing „Pro”'),
                             ('Детальніший дизайн, анімації, аналітика, адмін-панель', 'Dopracowany projekt, animacje, analityka, panel edycji'),
                             ('€450', '450 €'),
                             ('4–5 днів', '4–5 dni')],
                            [('Сайт-візитка', 'Strona wizytówka'),
                             ('One page або 1–5 сторінок: послуги, ціни, контакти, карта', 'One page lub 1–5 podstron: usługi, cennik, kontakt, mapa'),
                             ('від €300', 'od 300 €'),
                             ('від 3 днів', 'od 3 dni')],
                            [('Багатосторінковий / корпоративний', 'Strona firmowa'),
                             ('Розділи послуг, про компанію, кейси, блог, CMS', 'Podstrony usług, o firmie, realizacje, blog, CMS'),
                             ('від €450', 'od 450 €'),
                             ('15–25 робочих днів', '15–25 dni roboczych')],
                            [('Інтернет-магазин', 'Sklep internetowy'),
                             ('Каталог, кошик, оплата, доставка, WooCommerce', 'Katalog, koszyk, płatności, dostawa, WooCommerce'),
                             ('від €800', 'od 800 €'),
                             ('20–30 робочих днів', '20–30 dni roboczych')],
                            [('Складний магазин або сервіс', 'Rozbudowany sklep lub serwis'),
                             ('Фільтри, інтеграції, особистий кабінет, нестандартна логіка', 'Filtry, integracje, konto klienta, niestandardowa logika'),
                             ('після брифу', 'po briefie'),
                             ('30–45+ робочих днів', '30–45+ dni roboczych')]]),
                          ('p',
                           'Усі тарифи вже включають індивідуальний дизайн, мобільну версію, базову SEO-оптимізацію, допомогу з текстами і 30 днів підтримки після запуску. Детальніше про кожен '
                           'формат — на сторінках <a href="svc-lending">створення лендінгу</a> та <a href="svc-internet-magazyn">розробки інтернет-магазину</a>.',
                           'Każdy pakiet obejmuje indywidualny projekt, wersję mobilną, podstawowe SEO, pomoc z tekstami i 30 dni wsparcia po starcie. Więcej o poszczególnych formatach przeczytasz w opisach usług <a '
                           'href="svc-sait-vizytka">strony wizytówki</a> i <a href="svc-internet-magazyn">sklepu internetowego</a>.')]},
              {'h2_uk': 'Приховані витрати: що не входить у ціну розробки',
               'h2_pl': 'Ukryte koszty: czego nie ma w cenie wykonania',
               'blocks': [('p',
                           "Розробка — це разовий платіж. Але сайт живе роками, і частина витрат з'являється після запуску. Чесний підрядник називає їх одразу, щоб вони не стали сюрпризом.",
                           'Wykonanie strony to płatność jednorazowa. Ale strona działa latami i część kosztów pojawia się dopiero po starcie. Uczciwy wykonawca mówi o nich od razu, żeby nie były '
                           'niespodzianką.'),
                          ('ul',
                           [('<strong>Домен</strong> — щорічна оплата реєстратору. Радимо оформлювати його на себе, а не на розробника.',
                             '<strong>Domena</strong> — opłata co roku u rejestratora. Zawsze rejestruj ją na siebie albo na swoją firmę, nie na wykonawcę.'),
                            ('<strong>Хостинг</strong> — щомісячна або річна оплата. Для невеликих сайтів вистачає тарифу на кшталт Hostinger, для навантажених проєктів — VPS.',
                             '<strong>Hosting</strong> — opłata miesięczna lub roczna. Małym stronom wystarczy prosty pakiet, np. w Hostingerze, większym projektom — VPS.'),
                            ('<strong>Платні плагіни й платформи</strong> — ліцензії тем, плагінів WordPress або підписка Webflow. Уточнюйте, чи вони разові, чи щорічні.',
                             '<strong>Płatne wtyczki i platformy</strong> — licencje motywów i wtyczek WordPressa albo abonament Webflow. Dopytaj, czy są jednorazowe, czy odnawiane co roku.'),
                            ('<strong>Контент</strong> — фотосесія, копірайтинг, переклади на інші мови.', '<strong>Treści</strong> — sesja zdjęciowa, copywriting, tłumaczenia na inne języki.'),
                            ('<strong>Підтримка</strong> — оновлення, резервні копії, дрібні правки. У нас — від €20 на місяць після безкоштовних 30 днів.',
                             '<strong>Opieka techniczna</strong> — aktualizacje, kopie zapasowe, drobne poprawki. U nas od 20 € miesięcznie po darmowych 30 dniach.'),
                            ('<strong>Просування</strong> — SEO, реклама, профіль Google. Сайт без трафіку — це вітрина в порожньому провулку.',
                             '<strong>Promocja</strong> — SEO, reklama, Profil Firmy w Google. Strona bez ruchu to witryna w pustej bocznej uliczce.')]),
                          ('card',
                           'Попросіть підрядника окремим рядком прописати щорічні витрати на домен, хостинг і ліцензії. Якщо він не може цього зробити — ви не знаєте реальної вартості сайту.',
                           'Poproś wykonawcę, żeby osobną pozycją rozpisał roczne koszty domeny, hostingu i licencji. Jeśli nie potrafi tego zrobić — nie znasz prawdziwego kosztu strony.')]},
              {'h2_uk': 'Фрилансер, студія чи агенція: у чому різниця',
               'h2_pl': 'Freelancer, studio czy agencja: czym się różnią',
               'blocks': [('p', 'Цифри ринку змінюються постійно, тому порівнюємо не суми, а логіку ціни.', 'Stawki na rynku ciągle się zmieniają, więc porównujemy nie kwoty, tylko to, jak powstaje cena.'),
                          ('h3', 'Фрилансер на шаблоні', 'Freelancer na szablonie'),
                          ('p',
                           'Найдешевший варіант. Підходить, коли потрібно швидко й просто. Ризики: дизайн, як у тисяч інших сайтів, одна людина відповідає за все, і якщо вона зникне — доступи й '
                           'знання про сайт зникнуть разом із нею.',
                           'Najtańsza opcja. Sprawdzi się, gdy potrzebujesz czegoś szybko i prosto. Ryzyka: wygląd jak u tysięcy innych stron, jedna osoba odpowiada za wszystko, a gdy zniknie — razem '
                           'z nią znikają dostępy i wiedza o stronie.'),
                          ('h3', 'Невелика студія', 'Małe studio'),
                          ('p',
                           'Середній бюджет. Над проєктом працює команда — дизайнер, розробник, SEO-спеціаліст, — але ви спілкуєтеся напряму з виконавцем, без менеджерів-посередників. Так працюємо і '
                           'ми.',
                           'Średni budżet. Nad projektem pracuje zespół — projektant, programista, specjalista SEO — ale rozmawiasz bezpośrednio z wykonawcą, bez pośredników. Tak pracujemy my.'),
                          ('h3', 'Агенція', 'Agencja'),
                          ('p',
                           'Найдорожче. У ціні — акаунт-менеджери, процеси, дослідження, великі команди. Виправдано для складних продуктів і корпорацій, але для малого бізнесу часто означає '
                           'переплату за структуру, а не за результат.',
                           'Najdroższa opcja. W cenie są opiekunowie klienta, procesy, badania i duże zespoły. Ma to sens przy złożonych produktach i korporacjach, ale dla JDG czy małej spółki często '
                           'oznacza przepłacanie za strukturę, a nie za efekt.')]},
              {'h2_uk': 'Як читати комерційну пропозицію',
               'h2_pl': 'Jak czytać wycenę strony',
               'blocks': [('p',
                           'Дві пропозиції з однаковою сумою можуть містити зовсім різний обсяг робіт. Перш ніж порівнювати ціни, перевірте, що саме за ними стоїть.',
                           'Dwie oferty na tę samą kwotę mogą obejmować zupełnie inny zakres. Zanim porównasz ceny, sprawdź, co dokładnie się za nimi kryje.'),
                          ('ul',
                           [('Чи дизайн індивідуальний, чи це шаблон?', 'Czy projekt jest indywidualny, czy to szablon?'),
                            ('Скільки сторінок і які саме функції входять?', 'Ile podstron i jakie dokładnie funkcje są w cenie?'),
                            ('Хто пише тексти й готує фото?', 'Kto przygotowuje teksty i zdjęcia?'),
                            ('Чи є мобільна версія, базове SEO й аналітика?', 'Czy jest wersja mobilna, podstawowe SEO i analityka?'),
                            ('Чи отримаєте ви всі доступи: домен, хостинг, CMS?', 'Czy dostaniesz wszystkie dostępy: domenę, hosting, CMS?'),
                            ('Що буде після запуску і скільки коштує підтримка?', 'Co dzieje się po starcie i ile kosztuje opieka?')]),
                          ('p',
                           'Також дивіться на документи. Ми працюємо за договором і з фактурою, оплата поетапна — у EUR, USD або PLN. Якщо підрядник пропонує «все на словах», це теж ризик, і його '
                           'вартість ви дізнаєтеся пізніше.',
                           'Zwróć też uwagę na formalności. My pracujemy na podstawie umowy i wystawiamy fakturę, płatność jest etapowa — w EUR, USD lub PLN. Jeśli wykonawca proponuje „wszystko na słowo”, to '
                           'też jest ryzyko, a jego cenę poznasz później.')]},
              {'h2_uk': 'Чому найдешевший сайт часто стає найдорожчим',
               'h2_pl': 'Dlaczego najtańsza strona często okazuje się najdroższa',
               'blocks': [('p',
                           "До нас регулярно приходять із сайтами, які колись зробили «задешево». Типові історії: домен оформлено на розробника, який не виходить на зв'язок; сайт не відкривається "
                           'нормально на смартфоні; шаблон перевантажений плагінами і повільно вантажиться; змінити ціну можна лише через програміста.',
                           'Regularnie trafiają do nas firmy ze stronami zrobionymi kiedyś „po taniości”. Typowe historie: domena zarejestrowana na wykonawcę, który nie odbiera telefonu; strona źle '
                           'działa na smartfonie; szablon obciążony wtyczkami ładuje się wolno; zmiana ceny wymaga programisty.'),
                          ('p',
                           'У результаті бізнес платить двічі: спершу за перший сайт, потім — за новий. Нормальна мінімальна ціна — це не найменша сума на ринку, а та, за яку ви отримуєте сайт, що '
                           'працює, належить вам і не потребує переробки за рік.',
                           'W efekcie firma płaci dwa razy: najpierw za pierwszą stronę, potem za nową. Rozsądne minimum to nie najniższa kwota na rynku, tylko taka, za którą dostajesz działającą '
                           'stronę, która należy do Ciebie i nie wymaga przeróbki po roku.'),
                          ('card',
                           'Після здачі проєкту ми передаємо клієнту всі доступи — до сайту, домену, хостингу, CMS і сервісів. Сайт має належати вам, а не підряднику.',
                           'Po oddaniu projektu przekazujemy klientowi wszystkie dostępy — do strony, domeny, hostingu, CMS i zewnętrznych serwisów. Strona ma należeć do Ciebie, a nie do wykonawcy.')]},
              {'h2_uk': 'Як заощадити без шкоди для результату',
               'h2_pl': 'Jak zaoszczędzić i nie stracić na jakości',
               'blocks': [('ul',
                           [('Почніть із лендінгу чи візитки, а розширюйте сайт, коли бізнес покаже, що це потрібно.',
                             'Zacznij od landingu lub wizytówki, a rozbudowuj stronę, gdy rozwój firmy pokaże, że to potrzebne.'),
                            ('Підготуйте тексти, фото й приклади робіт заздалегідь — це скорочує терміни.', 'Przygotuj teksty, zdjęcia i realizacje z wyprzedzeniem — to skraca termin.'),
                            ('Погодьте структуру до старту дизайну. Зміни затвердженої структури посеред проєкту — найчастіша причина перегляду бюджету.',
                             'Ustal strukturę przed projektem graficznym. Zmiany w zaakceptowanej strukturze w trakcie projektu to najczęstszy powód korekty budżetu.'),
                            ('Збирайте правки одним списком, а не по одній у месенджері.', 'Zbieraj poprawki w jedną listę, zamiast wysyłać je pojedynczo w komunikatorze.'),
                            ('Не купуйте функції «на виріст» — додати їх пізніше зазвичай простіше, ніж здається.',
                             'Nie kupuj funkcji „na zapas” — dodanie ich później zwykle jest prostsze, niż się wydaje.')]),
                          ('p',
                           'Якщо сумніваєтеся, який формат потрібен, опишіть задачу через <a href="contacts">форму контактів</a> — порадимо, з чого почати, і надішлемо оцінку протягом 24 годин.',
                           'Jeśli nie wiesz, jaki format wybrać, opisz projekt w <a href="contacts">formularzu kontaktowym</a> — doradzimy, od czego zacząć, i wyślemy wycenę w ciągu 24 godzin.')]}],
 'faq': [['Скільки коштує сайт для малого бізнесу у 2026 році?',
          'Ile kosztuje strona dla małej firmy w 2026 roku?',
          'У нас сайт для малого бізнесу коштує від €300 за лендінг або візитку і від €450 за багатосторінковий сайт. Ціна включає індивідуальний дизайн, мобільну версію, базове SEO і 30 днів '
          'підтримки. Окремо варто закласти домен і хостинг, які оплачуються щороку, а також можливі платні плагіни.',
          'U nas strona dla małej firmy kosztuje od 300 € za landing lub wizytówkę i od 450 € za stronę firmową (cena końcowa, zw. z VAT). W cenie jest indywidualny projekt, wersja mobilna, podstawowe SEO i 30 dni '
          'wsparcia. Osobno trzeba doliczyć domenę i hosting, opłacane co roku, oraz ewentualne płatne wtyczki.'],
         ['Скільки часу займає створення сайту?',
          'Ile trwa wykonanie strony internetowej?',
          'Лендінг ми запускаємо за 3 дні, розширену версію — за 4–5 днів. Багатосторінковий сайт займає 15–25 робочих днів, інтернет-магазин — 20–30 робочих днів, складні магазини й сервіси — 30–45 '
          'робочих днів і більше. Терміни скорочуються, якщо тексти й фото готові до старту.',
          'Landing page uruchamiamy w 3 dni, wersję rozszerzoną w 4–5 dni. Strona firmowa zajmuje 15–25 dni roboczych, sklep internetowy 20–30 dni roboczych, a rozbudowane sklepy i serwisy 30–45 dni '
          'roboczych lub dłużej. Termin skraca się, gdy teksty i zdjęcia są gotowe przed startem.'],
         ['Які щорічні витрати на сайт після запуску?',
          'Jakie są roczne koszty utrzymania strony?',
          "Обов'язкові щорічні витрати — це домен і хостинг, які варто оформлювати на себе. До них можуть додатися ліцензії платних плагінів або підписка на платформу, наприклад Webflow. Якщо "
          'потрібні оновлення й дрібні правки, підтримка в нас коштує від €20 на місяць після 30 безкоштовних днів.',
          'Obowiązkowe koszty roczne to domena i hosting, które warto wykupić na własną firmę. Mogą do nich dojść licencje płatnych wtyczek lub abonament platformy, np. Webflow. Jeśli '
          'potrzebujesz aktualizacji i drobnych poprawek, opieka techniczna u nas kosztuje od 20 € miesięcznie po 30 darmowych dniach.'],
         ['Чому ціни на сайти так сильно відрізняються?',
          'Dlaczego ceny stron internetowych tak bardzo się różnią?',
          'Ціни відрізняються, бо різні підрядники пропонують різний обсяг робіт під тим самим словом «сайт». Шаблон без текстів і SEO коштує дешевше, ніж індивідуальний дизайн з аналітикою та '
          'підтримкою. Порівнюйте не суми, а перелік того, що входить у кожну пропозицію, і хто отримає доступи після запуску.',
          'Ceny się różnią, bo pod tym samym hasłem „strona” wykonawcy oferują zupełnie inny zakres. Szablon bez tekstów i SEO kosztuje mniej niż indywidualny projekt z analityką i opieką. Porównuj '
          'nie kwoty, tylko listę tego, co wchodzi w każdą ofertę, i to, kto dostanie dostępy po starcie.'],
         ['Чи можна оплатити сайт частинами?',
          'Czy za stronę można zapłacić w ratach?',
          'Так, ми працюємо з поетапною оплатою за договором і з фактурою, тож не потрібно платити всю суму одразу. Приймаємо оплату в EUR, USD або PLN. Точну вартість складних проєктів рахуємо '
          'після брифу й надсилаємо оцінку протягом 24 годин, щоб ви знали бюджет до початку робіт.',
          'Tak, płatność dzielimy na etapy, na podstawie umowy i faktury, więc nie musisz płacić całej kwoty od razu. Przyjmujemy EUR, USD lub PLN, a ceny są końcowe, bo korzystamy ze zwolnienia z VAT. Rozbudowane projekty wyceniamy po '
          'briefie i wysyłamy wycenę w ciągu 24 godzin, żebyś znał budżet przed startem.']],
 'service': 'prices',
 'cta_uk': 'Хочете знати точну ціну свого сайту? Перегляньте <a href="prices">наші ціни</a> або опишіть задачу — оцінку надішлемо протягом 24 годин.',
 'cta_pl': 'Chcesz poznać dokładną cenę swojej strony? Zajrzyj do <a href="prices">cennika</a> albo opisz projekt — wycenę wyślemy w ciągu 24 godzin.',
 'date': '2026-09-24'}
