# Дані сторінок кейсів (UA / PL). Факти — з аналізу живих сайтів клієнтів 24.09.2026.
# Без вигаданих цифр результатів: лише те, що видно на сайті.

CASES = [
  dict(slug="rozmarin", name="Rozmarin", url="https://rozmarin.shop/", img="assets/cases/case29.webp",
    title_uk="Інтернет-магазин квітів у Вроцлаві — кейс Rozmarin | Web Shestakov",
    title_pl="Sklep internetowy z kwiatami we Wrocławiu — realizacja Rozmarin | Web Shestakov",
    desc_uk="Як ми зробили інтернет-магазин квіткового бутика Rozmarin у Вроцлаві: WooCommerce, три мови, каталог композицій і преміум-колекція.",
    desc_pl="Jak stworzyliśmy sklep internetowy kwiaciarni Rozmarin we Wrocławiu: WooCommerce, trzy języki, katalog kompozycji i kolekcja premium.",
    h1_uk="Інтернет-магазин квітів у Вроцлаві", h1_pl="Sklep internetowy z kwiatami we Wrocławiu",
    sub_uk="Квітковий бутик Rozmarin продає авторські композиції онлайн — польською, англійською та українською.",
    sub_pl="Kwiaciarnia Rozmarin sprzedaje autorskie kompozycje online — po polsku, angielsku i ukraińsku.",
    facts=[("Тип","Typ","Інтернет-магазин","Sklep internetowy"),("Місто","Miasto","Вроцлав, Польща","Wrocław, Polska"),("Мови","Języki","PL · EN · UA","PL · EN · UA"),("Платформа","Platforma","WordPress + WooCommerce","WordPress + WooCommerce"),("Ніша","Branża","Квіти","Kwiaty")],
    task_uk="Бутику потрібен був магазин, у якому букет можна вибрати й оплатити за кілька хвилин — з телефона, будь-якою з трьох мов, якими говорять клієнти у Вроцлаві.",
    task_pl="Kwiaciarnia potrzebowała sklepu, w którym bukiet można wybrać i opłacić w kilka minut — z telefonu i w jednym z trzech języków, którymi mówią klienci we Wrocławiu.",
    sol_uk="Ми зробили елегантну вітрину з акцентом на фото композицій: окремий вибір «ідеальної композиції», преміум-колекцію, кошик і оформлення замовлення на WooCommerce, а також три мовні версії з hreflang.",
    sol_pl="Zrobiliśmy elegancką witrynę z naciskiem na zdjęcia kompozycji: wybór „idealnej kompozycji”, kolekcję premium, koszyk i zamówienia na WooCommerce oraz trzy wersje językowe z hreflang.",
    pills=[("Каталог","Katalog"),("Кошик і оплата","Koszyk i płatność"),("3 мови","3 języki"),("Преміум-колекція","Kolekcja premium"),("Мобільна версія","Wersja mobilna")],
    feats=[("Каталог композицій","Katalog kompozycji","Кожна композиція має власну картку з фото, ціною та кнопкою замовлення.","Każda kompozycja ma własną kartę ze zdjęciem, ceną i przyciskiem zamówienia."),
           ("Преміум-колекція","Kolekcja premium","Окремий блок для дорожчих букетів, щоб підняти середній чек.","Osobny blok z droższymi bukietami, który podnosi średnią wartość zamówienia."),
           ("Три мови","Trzy języki","Польська, англійська й українська версії з правильними hreflang для Google.","Wersje polska, angielska i ukraińska z poprawnym hreflang dla Google."),
           ("Замовлення онлайн","Zamówienia online","Кошик і оформлення на WooCommerce — клієнт замовляє без дзвінка.","Koszyk i zamówienia na WooCommerce — klient zamawia bez dzwonienia."),
           ("Адмінпанель","Panel administracyjny","Власник сам додає нові букети, змінює ціни й фото.","Właściciel sam dodaje nowe bukiety, zmienia ceny i zdjęcia.")]),

  dict(slug="bellissimo-home", name="Bellissimo Home", url="https://homebellissimowroclaw.com/", img="assets/cases/case17.webp",
    title_uk="Лендінг для салону італійських меблів у Вроцлаві — кейс Bellissimo Home",
    title_pl="Landing page dla salonu włoskich mebli we Wrocławiu — realizacja Bellissimo Home",
    desc_uk="Лендінг для шоуруму італійських меблів і кухонь на замовлення у Вроцлаві: калькулятор вартості, запис на зустріч, розділ для архітекторів.",
    desc_pl="Landing page dla showroomu włoskich mebli i kuchni na wymiar we Wrocławiu: kalkulator kosztów, rezerwacja spotkania, sekcja dla architektów.",
    h1_uk="Лендінг для салону італійських меблів", h1_pl="Landing page dla salonu włoskich mebli",
    sub_uk="Bellissimo Home — шоурум італійських меблів, кухонь і гардеробних на замовлення у Вроцлаві.",
    sub_pl="Bellissimo Home — showroom włoskich mebli, kuchni i garderob na wymiar we Wrocławiu.",
    facts=[("Тип","Typ","Лендінг","Landing page"),("Місто","Miasto","Вроцлав, Польща","Wrocław, Polska"),("Мова","Język","Польська","Polski"),("Функції","Funkcje","Калькулятор, бронювання","Kalkulator, rezerwacja"),("Ніша","Branża","Меблі та інтер'єри","Meble i wnętrza")],
    task_uk="Салону потрібен був сайт, який продає не окремі меблі, а комплексне облаштування інтер'єру — і приводить клієнтів у шоурум на зустріч.",
    task_pl="Salon potrzebował strony, która sprzedaje nie pojedyncze meble, ale kompleksowe wyposażenie wnętrz — i przyprowadza klientów do showroomu na spotkanie.",
    sol_uk="Ми побудували лендінг навколо шляху клієнта: для кого салон, рішення для кожного приміщення, візуалізації, калькулятор орієнтовної вартості, процес «від проєкту до доставки» і запис на зустріч у шоурумі.",
    sol_pl="Zbudowaliśmy landing wokół ścieżki klienta: dla kogo jest salon, rozwiązania do każdego pomieszczenia, wizualizacje, kalkulator orientacyjnego kosztu, proces „od projektu do dostawy” i rezerwacja spotkania w showroomie.",
    pills=[("Калькулятор","Kalkulator"),("Запис на зустріч","Rezerwacja"),("Для архітекторів","Dla architektów"),("Бренди","Marki"),("FAQ","FAQ")],
    feats=[("Калькулятор вартості","Kalkulator kosztów","Клієнт одразу бачить орієнтовний бюджет свого проєкту — менше «просто запитати ціну».","Klient od razu widzi orientacyjny budżet projektu — mniej pytań „ile to kosztuje”."),
           ("Рішення для кожного приміщення","Rozwiązania do każdego pomieszczenia","Кухні, гардеробні, освітлення й меблі зібрані в одну зрозумілу структуру.","Kuchnie, garderoby, oświetlenie i meble w jednej, czytelnej strukturze."),
           ("Співпраця з архітекторами","Współpraca z architektami","Окремий блок для дизайнерів інтер'єру — другий канал продажів.","Osobny blok dla projektantów wnętrz — drugi kanał sprzedaży."),
           ("Довіра","Zaufanie","Цифри компанії, бренди-партнери, відгуки клієнтів і партнерів.","Liczby firmy, marki partnerskie, opinie klientów i partnerów."),
           ("Запис у шоурум","Rezerwacja w showroomie","Форма бронювання зустрічі й адреса шоуруму наприкінці сторінки.","Formularz rezerwacji spotkania i adres showroomu na końcu strony.")]),

  dict(slug="td-solar", name="TD-SOLAR", url="https://tdsolarenergy.com/", img="assets/cases/case10.webp",
    title_uk="Лендінг для монтажу сонячних панелей у Німеччині — кейс TD-SOLAR",
    title_pl="Landing page dla montażu fotowoltaiki w Niemczech — realizacja TD-SOLAR",
    desc_uk="Лендінг німецькою для бригади DC-монтажу фотоелектричних станцій: послуги, процес співпраці, обладнання, приклади робіт і форма запиту.",
    desc_pl="Landing page po niemiecku dla ekipy montażu DC instalacji fotowoltaicznych: usługi, proces współpracy, sprzęt, realizacje i formularz zapytania.",
    h1_uk="Лендінг для монтажу сонячних панелей", h1_pl="Landing page dla montażu fotowoltaiki",
    sub_uk="TD-SOLAR — бригада DC-монтажу фотоелектричних станцій по всій Німеччині.",
    sub_pl="TD-SOLAR — ekipa montażu DC instalacji fotowoltaicznych w całych Niemczech.",
    facts=[("Тип","Typ","Лендінг","Landing page"),("Країна","Kraj","Німеччина","Niemcy"),("Мова","Język","Німецька","Niemiecki"),("Аудиторія","Odbiorcy","B2B, генпідрядники","B2B, generalni wykonawcy"),("Ніша","Branża","Сонячна енергетика","Fotowoltaika")],
    task_uk="Бригаді потрібні були замовлення від німецьких компаній, які будують сонячні станції. Сайт мав говорити їхньою мовою — і буквально, і професійно.",
    task_pl="Ekipa potrzebowała zleceń od niemieckich firm budujących instalacje fotowoltaiczne. Strona miała mówić ich językiem — dosłownie i branżowo.",
    sol_uk="Ми зробили B2B-лендінг німецькою: повний спектр робіт на DC-стороні, процес співпраці крок за кроком, обладнання за німецькими стандартами, фото з об'єктів, FAQ і форма запиту на монтаж.",
    sol_pl="Zrobiliśmy landing B2B po niemiecku: pełny zakres prac po stronie DC, proces współpracy krok po kroku, sprzęt według niemieckich standardów, zdjęcia z realizacji, FAQ i formularz zapytania.",
    pills=[("B2B","B2B"),("Німецька мова","Język niemiecki"),("Процес","Proces"),("Фото з об'єктів","Zdjęcia z realizacji"),("Форма запиту","Formularz")],
    feats=[("Спектр послуг","Zakres usług","Модулі, підконструкції, DC-кабелі, заземлення, кабель-канали, захист від птахів, фотодокументація.","Moduły, konstrukcje, kable DC, uziemienie, korytka, ochrona przed ptakami, dokumentacja zdjęciowa."),
           ("Процес співпраці","Proces współpracy","Замовник бачить, як бригада працює від запиту до здачі об'єкта.","Zleceniodawca widzi, jak ekipa pracuje od zapytania do odbioru."),
           ("Якість і обладнання","Jakość i sprzęt","Окремий блок про інструменти й стандарти — головний аргумент для німецького B2B.","Osobny blok o narzędziach i standardach — kluczowy argument w niemieckim B2B."),
           ("Приклади робіт","Realizacje","Фото з реальних монтажів замість стокових картинок.","Zdjęcia z prawdziwych montaży zamiast zdjęć stockowych."),
           ("Запит на монтаж","Zapytanie o montaż","Дві форми на сторінці: зверху й наприкінці, після FAQ.","Dwa formularze na stronie: na górze i na końcu, po FAQ.")]),

  dict(slug="tarik-invest", name="TARIK Invest", url="https://tarikinvest.cz/", img="assets/cases/case18.webp",
    title_uk="Сайт для електромонтажної компанії в Чехії — кейс TARIK Invest",
    title_pl="Strona dla firmy elektroinstalacyjnej w Czechach — realizacja TARIK Invest",
    desc_uk="Сайт на Next.js для електромонтажної компанії в Чехії: чеська й українська версії, процес без хаосу, відгуки, вакансії та FAQ.",
    desc_pl="Strona na Next.js dla firmy elektroinstalacyjnej w Czechach: wersja czeska i ukraińska, uporządkowany proces, opinie, rekrutacja i FAQ.",
    h1_uk="Сайт для електромонтажної компанії", h1_pl="Strona dla firmy elektroinstalacyjnej",
    sub_uk="TARIK Invest виконує електромонтаж на великих об'єктах по всій Чехії.",
    sub_pl="TARIK Invest wykonuje instalacje elektryczne na dużych obiektach w całych Czechach.",
    facts=[("Тип","Typ","Лендінг","Landing page"),("Країна","Kraj","Чехія","Czechy"),("Мови","Języki","CS · UA","CS · UA"),("Платформа","Platforma","Next.js","Next.js"),("Ніша","Branża","Електромонтаж","Elektroinstalacje")],
    task_uk="Компанії потрібно було одночасно продавати послуги великим замовникам і наймати електриків — і все це на одному сайті, двома мовами.",
    task_pl="Firma chciała jednocześnie sprzedawać usługi dużym zleceniodawcom i rekrutować elektryków — na jednej stronie, w dwóch językach.",
    sol_uk="Ми зробили швидкий сайт на Next.js: комплексні послуги «під одним дахом», керований процес на будові, аргументи для великих проєктів, відгуки, окремий блок вакансій і FAQ — чеською та українською.",
    sol_pl="Zrobiliśmy szybką stronę na Next.js: kompleksowe usługi „pod jednym dachem”, uporządkowany proces na budowie, argumenty dla dużych projektów, opinie, sekcja rekrutacji i FAQ — po czesku i po ukraińsku.",
    pills=[("Next.js","Next.js"),("CS / UA","CS / UA"),("B2B","B2B"),("Вакансії","Rekrutacja"),("FAQ","FAQ")],
    feats=[("Дві мови","Dwa języki","Чеська для замовників і українська для електриків, які шукають роботу.","Czeski dla zleceniodawców i ukraiński dla elektryków szukających pracy."),
           ("Послуги під одним дахом","Usługi pod jednym dachem","Сильнострум, слабкострум і монтаж «під ключ» для житлових, комерційних і промислових об'єктів.","Silnoprąd, słaboprąd i instalacje pod klucz dla obiektów mieszkaniowych, komercyjnych i przemysłowych."),
           ("Процес без хаосу","Proces bez chaosu","Блок, який знімає головний страх замовника — зрив строків на будові.","Blok, który odpowiada na największą obawę zleceniodawcy — opóźnienia na budowie."),
           ("Найм електриків","Rekrutacja elektryków","Окремий розділ вакансій — сайт працює і на продажі, і на HR.","Osobna sekcja rekrutacji — strona pracuje i na sprzedaż, i na HR."),
           ("Швидкість","Szybkość","Next.js дає швидке завантаження навіть на мобільному інтернеті на будові.","Next.js zapewnia szybkie ładowanie nawet na mobilnym internecie na budowie.")]),

  dict(slug="dictator-barbershop", name="DICTATOR", url="https://dictatorbarbershop.com/", img="assets/cases/case31.webp",
    title_uk="Сайт для мережі барбершопів — кейс DICTATOR, Дніпро | Web Shestakov",
    title_pl="Strona dla sieci barber shopów — realizacja DICTATOR | Web Shestakov",
    desc_uk="Багатосторінковий сайт для преміальної мережі барбершопів DICTATOR у Дніпрі: вибір філії, онлайн-запис, майстри, акції, Barber Academy і франшиза.",
    desc_pl="Strona wielostronicowa dla sieci barber shopów premium DICTATOR w Dnieprze: wybór salonu, rezerwacja online, barberzy, promocje, akademia i franczyza.",
    h1_uk="Сайт для мережі барбершопів", h1_pl="Strona dla sieci barber shopów",
    sub_uk="DICTATOR — преміальна мережа барбершопів у Дніпрі зі школою барберів і франшизою.",
    sub_pl="DICTATOR — sieć barber shopów premium w Dnieprze ze szkołą barberów i franczyzą.",
    facts=[("Тип","Typ","Багатосторінковий","Wielostronicowa"),("Місто","Miasto","Дніпро, Україна","Dniepr, Ukraina"),("Мова","Język","Українська","Ukraiński"),("Платформа","Platforma","WordPress","WordPress"),("Ніша","Branża","Барбершопи","Barber shopy")],
    task_uk="Мережі з кількома філіями потрібен був один сайт, який веде клієнта до запису в потрібну філію, продає навчання в академії та франшизу.",
    task_pl="Sieć z kilkoma salonami potrzebowała jednej strony, która prowadzi klienta do rezerwacji w wybranym salonie, sprzedaje szkolenia w akademii i franczyzę.",
    sol_uk="Ми зробили сайт у темному преміальному стилі бренду: послуги, вибір філії, онлайн-запис, акції, майстри, галерея, Barber Academy, розділ франшизи, відгуки й контакти.",
    sol_pl="Zrobiliśmy stronę w ciemnym, premium stylu marki: usługi, wybór salonu, rezerwacja online, promocje, barberzy, galeria, Barber Academy, franczyza, opinie i kontakt.",
    pills=[("Онлайн-запис","Rezerwacja online"),("Філії","Salony"),("Академія","Akademia"),("Франшиза","Franczyza"),("WordPress","WordPress")],
    feats=[("Вибір філії","Wybór salonu","Клієнт одразу обирає найближчий барбершоп мережі.","Klient od razu wybiera najbliższy salon sieci."),
           ("Онлайн-запис","Rezerwacja online","Запис на стрижку без дзвінка — прямо з сайту.","Rezerwacja strzyżenia bez dzwonienia — prosto ze strony."),
           ("Майстри і галерея","Barberzy i galeria","Обличчя команди та роботи — те, за чим обирають барбершоп.","Zespół i realizacje — to, po czym wybiera się barber shop."),
           ("Barber Academy","Barber Academy","Окремий напрям для тих, хто хоче стати барбером.","Osobny kierunek dla osób, które chcą zostać barberem."),
           ("Франшиза","Franczyza","Блок «Станьте частиною мережі» для партнерів.","Blok „Dołącz do sieci” dla partnerów.")]),

  dict(slug="elart-cleaning", name="Elart Cleaning", url="https://cleaningelart.pl/", img="assets/cases/case16.webp",
    title_uk="Лендінг для клінінгової компанії в Познані — кейс Elart Cleaning",
    title_pl="Landing page dla firmy sprzątającej w Poznaniu — realizacja Elart Cleaning",
    desc_uk="Лендінг на Next.js для клінінгової компанії в Познані: прайс і пакети, 7 кроків співпраці, фото до/після, відгуки 4.9/5 і онлайн-бронювання.",
    desc_pl="Landing page na Next.js dla firmy sprzątającej w Poznaniu: cennik i pakiety, 7 kroków współpracy, zdjęcia przed i po, opinie 4.9/5 i rezerwacja online.",
    h1_uk="Лендінг для клінінгової компанії", h1_pl="Landing page dla firmy sprzątającej",
    sub_uk="Elart Cleaning — прибирання квартир, будинків і офісів, хімчистка меблів і переїзди в Познані.",
    sub_pl="Elart Cleaning — sprzątanie mieszkań, domów i biur, pranie tapicerki i przeprowadzki w Poznaniu.",
    facts=[("Тип","Typ","Лендінг","Landing page"),("Місто","Miasto","Познань, Польща","Poznań, Polska"),("Мова","Język","Польська","Polski"),("Платформа","Platforma","Next.js","Next.js"),("Ніша","Branża","Клінінг","Sprzątanie")],
    task_uk="У клінінгу клієнт обирає за ціною та довірою. Сайт мав одразу показати прозорі ціни й переконати, що в дім прийдуть надійні люди.",
    task_pl="W sprzątaniu klient wybiera po cenie i zaufaniu. Strona miała od razu pokazać przejrzysty cennik i przekonać, że do domu przyjdą rzetelni ludzie.",
    sol_uk="Ми зробили лендінг польською з прозорим прайсом і пакетами, «7 кроків від контакту до чистоти», стабільною командою, фото до/після, відгуками з оцінкою 4.9/5, FAQ і бронюванням.",
    sol_pl="Zrobiliśmy landing po polsku z przejrzystym cennikiem i pakietami, „7 krokami od kontaktu do czystej przestrzeni”, stałą ekipą, zdjęciami przed i po, opiniami 4.9/5, FAQ i rezerwacją.",
    pills=[("Прайс і пакети","Cennik i pakiety"),("До / після","Przed i po"),("Відгуки 4.9","Opinie 4.9"),("Бронювання","Rezerwacja"),("Next.js","Next.js")],
    feats=[("Прозорий прайс","Przejrzysty cennik","Пакети прибирання квартир і повний список послуг з цінами.","Pakiety sprzątania mieszkań i pełna lista usług z cenami."),
           ("7 кроків","7 kroków","Клієнт бачить увесь шлях: від заявки до чистої квартири.","Klient widzi całą ścieżkę: od kontaktu do czystego mieszkania."),
           ("Команда","Zespół","«Стала команда, якій не байдуже» — довіра до людей, які приходять у дім.","„Stała ekipa, której naprawdę zależy” — zaufanie do osób, które wchodzą do domu."),
           ("До і після","Przed i po","Фото результатів говорять краще за будь-які тексти.","Zdjęcia efektów mówią więcej niż jakikolwiek tekst."),
           ("Бронювання","Rezerwacja","Швидка оцінка й запис на прибирання прямо з сайту.","Szybka wycena i rezerwacja sprzątania prosto ze strony.")]),

  dict(slug="core-accounting", name="Core Accounting", url="https://core-accounting.net/", img="assets/cases/case13.webp",
    title_uk="Сайт для бухгалтерської компанії на Webflow — кейс Core Accounting",
    title_pl="Strona dla biura rachunkowego na Webflow — realizacja Core Accounting",
    desc_uk="Багатосторінковий сайт на Webflow для бухгалтерської компанії Core Accounting: позиціонування, цільова аудиторія, відгуки та форма заявки.",
    desc_pl="Strona wielostronicowa na Webflow dla biura rachunkowego Core Accounting: pozycjonowanie, grupa docelowa, opinie i formularz kontaktowy.",
    h1_uk="Сайт для бухгалтерської компанії", h1_pl="Strona dla biura rachunkowego",
    sub_uk="Core Accounting — бухгалтерія як «ядро бізнесу і фундамент, без якого все руйнується».",
    sub_pl="Core Accounting — księgowość jako „rdzeń biznesu i fundament, bez którego wszystko się rozpada”.",
    facts=[("Тип","Typ","Багатосторінковий","Wielostronicowa"),("Мова","Język","Українська","Ukraiński"),("Платформа","Platforma","Webflow","Webflow"),("Керування","Zarządzanie","Webflow CMS","Webflow CMS"),("Ніша","Branża","Бухгалтерія","Księgowość")],
    task_uk="Бухгалтерські послуги схожі між собою. Компанії потрібно було виділитися чіткою ідеєю і показати, для кого саме вона працює.",
    task_pl="Usługi księgowe są do siebie podobne. Firma chciała wyróżnić się wyraźną ideą i pokazać, dla kogo dokładnie pracuje.",
    sol_uk="Ми зробили сайт на Webflow навколо метафори «ядра» бізнесу: сильне позиціонування, блок цільової аудиторії, відгуки клієнтів і форма заявки. Контент власник змінює сам через CMS.",
    sol_pl="Zrobiliśmy stronę na Webflow wokół metafory „rdzenia” biznesu: mocne pozycjonowanie, blok grupy docelowej, opinie klientów i formularz. Treści właściciel zmienia sam w CMS.",
    pills=[("Webflow","Webflow"),("Позиціонування","Pozycjonowanie"),("Цільова аудиторія","Grupa docelowa"),("Відгуки","Opinie"),("CMS","CMS")],
    feats=[("Ідея бренду","Idea marki","Бухгалтерія як фундамент бізнесу — зрозуміла метафора замість сухого переліку послуг.","Księgowość jako fundament biznesu — czytelna metafora zamiast suchej listy usług."),
           ("Для кого","Dla kogo","Окремий блок цільової аудиторії: клієнт одразу впізнає себе.","Osobny blok grupy docelowej: klient od razu rozpoznaje siebie."),
           ("Відгуки","Opinie","Слова реальних клієнтів — головний аргумент у фінансових послугах.","Słowa prawdziwych klientów — główny argument w usługach finansowych."),
           ("Webflow CMS","Webflow CMS","Власник оновлює тексти без розробника.","Właściciel aktualizuje treści bez programisty."),
           ("Заявка","Formularz","Форма зв'язку, яка веде до консультації.","Formularz kontaktowy prowadzący do konsultacji.")]),

  dict(slug="nagachky-sushi", name="Nagachky Sushi", url="https://nagachkysushi.com/", img="assets/cases/case6.webp",
    title_uk="Сайт доставки суші з онлайн-замовленням — кейс Nagachky Sushi",
    title_pl="Strona z dostawą sushi i zamówieniami online — realizacja Nagachky Sushi",
    desc_uk="Сайт доставки суші на WordPress + WooCommerce: меню з кошиком, авторські пропозиції, адреса закладу та FAQ.",
    desc_pl="Strona z dostawą sushi na WordPress + WooCommerce: menu z koszykiem, autorskie propozycje, lokalizacja i FAQ.",
    h1_uk="Сайт доставки суші з онлайн-замовленням", h1_pl="Strona z dostawą sushi i zamówieniami online",
    sub_uk="Nagachky Sushi — «роли з душею, доставка з турботою».",
    sub_pl="Nagachky Sushi — „rolki z duszą, dostawa z troską”.",
    facts=[("Тип","Typ","Багатосторінковий","Wielostronicowa"),("Країна","Kraj","Україна","Ukraina"),("Мова","Język","Українська","Ukraiński"),("Платформа","Platforma","WordPress + WooCommerce","WordPress + WooCommerce"),("Ніша","Branża","Доставка суші","Dostawa sushi")],
    task_uk="Закладу доставки потрібен був власний канал замовлень — без комісій агрегаторів і з меню, яке легко оновлювати.",
    task_pl="Lokal z dostawą potrzebował własnego kanału zamówień — bez prowizji agregatorów i z menu, które łatwo aktualizować.",
    sol_uk="Ми зробили сайт із повним меню на WooCommerce: кошик, оформлення замовлення, авторські пропозиції, блок «де ми знаходимось» і FAQ. Меню й ціни власник змінює в адмінпанелі.",
    sol_pl="Zrobiliśmy stronę z pełnym menu na WooCommerce: koszyk, zamówienie, autorskie propozycje, lokalizacja i FAQ. Menu i ceny właściciel zmienia w panelu.",
    pills=[("Онлайн-меню","Menu online"),("Кошик","Koszyk"),("Доставка","Dostawa"),("WooCommerce","WooCommerce"),("FAQ","FAQ")],
    feats=[("Меню з кошиком","Menu z koszykiem","Усі роли й сети з фото та цінами — замовлення в кілька кліків.","Wszystkie rolki i zestawy ze zdjęciami i cenami — zamówienie w kilka kliknięć."),
           ("Авторські пропозиції","Autorskie propozycje","Окремий блок для фірмових позицій закладу.","Osobny blok z firmowymi pozycjami lokalu."),
           ("Власний канал продажів","Własny kanał sprzedaży","Замовлення напряму, без комісії агрегаторів.","Zamówienia bezpośrednio, bez prowizji agregatorów."),
           ("Локація і FAQ","Lokalizacja i FAQ","Адреса закладу й відповіді про доставку та оплату.","Adres lokalu i odpowiedzi o dostawie i płatności."),
           ("Керування меню","Zarządzanie menu","Нові позиції, ціни й фото — через адмінпанель.","Nowe pozycje, ceny i zdjęcia — w panelu administracyjnym.")]),

  dict(slug="herstel-bouw", name="Herstel & Bouw", url="https://herstelenbouw.nl/", img="assets/cases/case35.webp",
    title_uk="Сайт для ремонтно-будівельної компанії в Нідерландах — кейс Herstel & Bouw",
    title_pl="Strona dla firmy remontowo-budowlanej w Holandii — realizacja Herstel & Bouw",
    desc_uk="Сайт для компанії з ремонту та будівництва в Амстердамі, Алмере й Утрехті: калькулятор вартості ремонту, портфоліо, відгуки, FAQ, нідерландська й англійська.",
    desc_pl="Strona dla firmy remontowo-budowlanej z Amsterdamu, Almere i Utrechtu: kalkulator kosztów remontu, realizacje, opinie, FAQ, wersja niderlandzka i angielska.",
    h1_uk="Сайт для ремонтно-будівельної компанії", h1_pl="Strona dla firmy remontowo-budowlanej",
    sub_uk="Herstel & Bouw — ремонт, перепланування й будівництво «від проєкту до оздоблення» в Нідерландах.",
    sub_pl="Herstel & Bouw — remonty, przebudowy i budowa „od projektu do wykończenia” w Holandii.",
    facts=[("Тип","Typ","Багатосторінковий","Wielostronicowa"),("Міста","Miasta","Амстердам, Алмере, Утрехт","Amsterdam, Almere, Utrecht"),("Мови","Języki","NL · EN","NL · EN"),("Функції","Funkcje","Калькулятор ремонту","Kalkulator remontu"),("Ніша","Branża","Будівництво","Budownictwo")],
    task_uk="У ремонті перше питання клієнта — «скільки це коштуватиме?». Сайт мав відповісти на нього ще до дзвінка і показати реальні об'єкти.",
    task_pl="W remontach pierwsze pytanie klienta brzmi: „ile to będzie kosztować?”. Strona miała odpowiedzieć na nie jeszcze przed telefonem i pokazać prawdziwe realizacje.",
    sol_uk="Ми зробили сайт із покроковим калькулятором вартості ремонту, портфоліо проєктів, блоком «чому ми» (фіксована ціна, 5 років гарантії), відгуками, партнерами, FAQ і трьома формами заявки.",
    sol_pl="Zrobiliśmy stronę z kalkulatorem kosztów remontu krok po kroku, portfolio realizacji, blokiem „dlaczego my” (stała cena, 5 lat gwarancji), opiniami, partnerami, FAQ i trzema formularzami.",
    pills=[("Калькулятор","Kalkulator"),("Портфоліо","Realizacje"),("NL / EN","NL / EN"),("Відгуки","Opinie"),("3 форми","3 formularze")],
    feats=[("Калькулятор ремонту","Kalkulator remontu","Клієнт крок за кроком рахує орієнтовну вартість свого проєкту.","Klient krok po kroku liczy orientacyjny koszt swojego projektu."),
           ("Проєкти","Realizacje","Реальні об'єкти компанії — доказ якості.","Prawdziwe realizacje firmy — dowód jakości."),
           ("Аргументи","Argumenty","Фіксована ціна наперед і 5 років гарантії — у першому екрані опису.","Stała cena z góry i 5 lat gwarancji — widoczne od razu."),
           ("Регіони","Regiony","Амстердам, Алмере, Утрехт, Північна й Південна Голландія — під локальний пошук.","Amsterdam, Almere, Utrecht, Holandia Północna i Południowa — pod wyszukiwanie lokalne."),
           ("Заявки","Zapytania","Три форми в різних місцях сторінки — клієнт пише тоді, коли готовий.","Trzy formularze w różnych miejscach — klient pisze, gdy jest gotowy.")]),

  dict(slug="kora-candle", name="Kora Candle", url="https://koracandle.com/", img="assets/cases/case14.webp",
    title_uk="Інтернет-магазин свічок ручної роботи — кейс Kora Candle | Web Shestakov",
    title_pl="Sklep internetowy ze świecami ręcznie robionymi — realizacja Kora Candle",
    desc_uk="Інтернет-магазин на WooCommerce для бренду свічок ручної роботи Kora Candle: каталог, подарункові набори, декор і запис на майстер-класи.",
    desc_pl="Sklep na WooCommerce dla marki ręcznie robionych świec Kora Candle: katalog, zestawy prezentowe, dekoracje i zapisy na warsztaty.",
    h1_uk="Інтернет-магазин свічок ручної роботи", h1_pl="Sklep internetowy ze świecami ręcznie robionymi",
    sub_uk="Kora Candle — свічки з натурального воску в дерев'яних кашпо, декоровані стабілізованими сухоцвітами.",
    sub_pl="Kora Candle — świece z naturalnego wosku w drewnianych donicach, zdobione stabilizowanymi suszonymi kwiatami.",
    facts=[("Тип","Typ","Інтернет-магазин","Sklep internetowy"),("Країна","Kraj","Україна","Ukraina"),("Мова","Język","Українська","Ukraiński"),("Платформа","Platforma","WordPress + WooCommerce","WordPress + WooCommerce"),("Ніша","Branża","Свічки й декор","Świece i dekoracje")],
    task_uk="Бренду ручної роботи потрібен був магазин, який передає атмосферу продукту, продає подарунки й записує людей на майстер-класи.",
    task_pl="Marka rękodzieła potrzebowała sklepu, który oddaje klimat produktu, sprzedaje prezenty i zapisuje na warsztaty.",
    sol_uk="Ми зробили магазин на WooCommerce з категоріями (свічки в кашпо, формові, декор, аксесуари, подарункові набори, кашпо), фільтром «в наявності» й окремим напрямом майстер-класів — індивідуальних і корпоративних.",
    sol_pl="Zrobiliśmy sklep na WooCommerce z kategoriami (świece w donicach, świece formowane, dekoracje, akcesoria, zestawy prezentowe, donice), filtrem „dostępne” i osobnym kierunkiem warsztatów — indywidualnych i firmowych.",
    pills=[("Каталог","Katalog"),("Подарункові набори","Zestawy prezentowe"),("Майстер-класи","Warsztaty"),("WooCommerce","WooCommerce"),("В наявності","Dostępne")],
    feats=[("Категорії","Kategorie","Свічки в кашпо, формові, декор, аксесуари, набори й кашпо — легко знайти потрібне.","Świece w donicach, formowane, dekoracje, akcesoria, zestawy i donice — łatwo znaleźć to, czego szukasz."),
           ("Подарунки","Prezenty","Подарункові набори — окремий сценарій покупки.","Zestawy prezentowe — osobny scenariusz zakupu."),
           ("Майстер-класи","Warsztaty","Індивідуальні й корпоративні майстер-класи — додатковий дохід бренду.","Warsztaty indywidualne i firmowe — dodatkowy przychód marki."),
           ("В наявності","Dostępne od ręki","Окремий розділ з товарами, які можна купити одразу.","Osobna sekcja z produktami dostępnymi od ręki."),
           ("Атмосфера","Klimat","Теплий візуал і фото продукту передають ручну роботу.","Ciepła oprawa i zdjęcia produktu oddają charakter rękodzieła.")]),
]
