# Тексти сторінок «Ціни» (/tsiny/, /pl/cennik/) і «Контакти» (/kontakty/, /pl/kontakt/).
# Лише затверджені ціни й умови (див. _seo/відповіді-про-нас-і-процес.md).

PRICES = dict(
  title_uk="Ціни на створення сайтів у 2026 році — від €300 | SHSTKV Digital",
  title_pl="Cennik stron internetowych 2026 — od 300 € | SHSTKV Digital",
  desc_uk="Скільки коштує сайт у 2026: лендінг від €300, багатосторінковий сайт від €450, інтернет-магазин від €800, підтримка від €20/міс. Договір і faktura.",
  desc_pl="Ile kosztuje strona internetowa w 2026: landing page od 300 €, strona firmowa od 450 €, sklep internetowy od 800 €, opieka od 20 €/mies. Umowa i faktura.",
  h1_uk="Ціни на створення сайтів у 2026 році",
  h1_pl="Cennik stron internetowych na 2026 rok",
  sub_uk="Фіксована ціна під ключ, договір і faktura, оплата поетапно в EUR, USD або PLN.",
  sub_pl="Stała cena pod klucz, umowa i faktura, płatność etapami w EUR, USD lub PLN.",
  facts=[
    ["Лендінг", "Landing page", "від €300", "od 300 €"],
    ["Багатосторінковий сайт", "Strona firmowa", "від €450", "od 450 €"],
    ["Інтернет-магазин", "Sklep internetowy", "від €800", "od 800 €"],
    ["Підтримка", "Opieka", "від €20 / міс.", "od 20 €/mies."],
    ["Складні проєкти", "Złożone projekty", "оцінка за 24 год", "wycena w 24 h"],
  ],
  plans_lead_uk="Ціни нижче — стартові варіанти для малого бізнесу. Складніші проєкти рахуємо під задачу: після короткого брифу надсилаємо оцінку протягом 24 годин.",
  plans_lead_pl="Poniższe ceny to pakiety startowe dla małych firm. Bardziej złożone projekty wyceniamy indywidualnie: po krótkim briefie wysyłamy wycenę w ciągu 24 godzin. Ceny są końcowe — nie doliczamy VAT (zwolnienie z VAT).",
  plans=[
    dict(price="300", from_=False, unit_uk="/ проєкт", unit_pl="/ projekt", tag_uk="Запуск за 3 дні", tag_pl="Start w 3 dni",
         name_uk="Старт", name_pl="Start",
         desc_uk="Лендінг або проста сторінка компанії для швидкого запуску, перевірки ідеї чи старту реклами.",
         desc_pl="Landing page lub prosta strona firmy — na szybki start, test pomysłu albo kampanię reklamową.",
         feats=[["Індивідуальний дизайн", "Indywidualny projekt graficzny"], ["Адаптація під мобільні пристрої", "Wersja mobilna"],
                ["Базова SEO-оптимізація", "Podstawowa optymalizacja SEO"], ["Форма заявки з відправкою в Telegram", "Formularz z wysyłką zgłoszeń na Telegram"],
                ["Допомога з текстами", "Pomoc przy tekstach"], ["30 днів підтримки після запуску", "30 dni wsparcia po starcie"]]),
    dict(price="450", from_=False, rec=True, badge_uk="Оптимальний вибір", badge_pl="Optymalny wybór",
         unit_uk="/ проєкт", unit_pl="/ projekt", tag_uk="Запуск за 4–5 днів", tag_pl="Start w 4–5 dni",
         name_uk="Про", name_pl="Pro",
         desc_uk="Для бізнесу, якому потрібен сильніший дизайн, більше функцій і можливість самому редагувати сайт.",
         desc_pl="Dla firm, które potrzebują mocniejszego designu, więcej funkcji i samodzielnej edycji strony.",
         feats=[["Усе з тарифу «Старт»", "Wszystko z pakietu Start"], ["Деталізованіший дизайн", "Bardziej dopracowany design"],
                ["Анімації та мікровзаємодії", "Animacje i mikrointerakcje"], ["Розширена робота з текстами", "Rozszerzona praca nad tekstami"],
                ["Підключення аналітики", "Podłączenie analityki"], ["Адмін-панель для редагування", "Panel do edycji treści"],
                ["30 днів підтримки після запуску", "30 dni wsparcia po starcie"]]),
  ],
  addons=[
    dict(price="450", from_=True, unit_uk="/ проєкт", unit_pl="/ projekt", name_uk="Багатосторінковий сайт", name_pl="Strona firmowa",
         tag_uk="15–25 роб. днів", tag_pl="15–25 dni rob.",
         desc_uk="Сайт компанії з окремими сторінками послуг, кейсами, блогом і кількома мовами. Ціна залежить від кількості сторінок і функцій.",
         desc_pl="Strona firmy z osobnymi podstronami usług, realizacjami, blogiem i kilkoma językami. Cena zależy od liczby podstron i funkcji.",
         cta_uk="Детальніше", cta_pl="Szczegóły", href="svc-korporatyvnyi-sait"),
    dict(price="800", from_=True, unit_uk="/ проєкт", unit_pl="/ projekt", name_uk="Інтернет-магазин", name_pl="Sklep internetowy",
         tag_uk="20–30 роб. днів", tag_pl="20–30 dni rob.",
         desc_uk="Каталог, кошик, онлайн-оплата, доставка й адмінка. Складні магазини з CRM та інтеграціями — 30–45+ робочих днів.",
         desc_pl="Katalog, koszyk, płatności online, dostawa i panel. Złożone sklepy z CRM i integracjami — 30–45+ dni roboczych.",
         cta_uk="Детальніше", cta_pl="Szczegóły", href="svc-internet-magazyn"),
    dict(price="20", from_=True, unit_uk="/ місяць", unit_pl="/ miesiąc", name_uk="Підтримка сайту", name_pl="Opieka nad stroną",
         tag_uk="Щомісяця", tag_pl="Co miesiąc",
         desc_uk="Технічний супровід після запуску: оновлення, невеликі правки, консультації та допомога з обслуговуванням.",
         desc_pl="Opieka techniczna po starcie: aktualizacje, drobne poprawki, konsultacje i pomoc w utrzymaniu strony.",
         cta_uk="Додати підтримку", cta_pl="Dodaj opiekę"),
    dict(price=None, name_uk="Telegram-бот", name_pl="Bot Telegram", tag_uk="Індивідуально", tag_pl="Indywidualnie",
         desc_uk="Бот для заявок, бронювань, продажів або внутрішніх процесів. Ціну й термін рахуємо після опису функцій.",
         desc_pl="Bot do zgłoszeń, rezerwacji, sprzedaży lub procesów wewnętrznych. Cenę i termin ustalamy, gdy poznamy listę funkcji.",
         cta_uk="Детальніше", cta_pl="Szczegóły", href="svc-telegram-bot"),
    dict(price=None, name_uk="SEO та айдентика", name_pl="SEO i identyfikacja wizualna", tag_uk="Після брифу", tag_pl="Po briefie",
         desc_uk="SEO-аудит і просування, логотип і фірмовий стиль. Обсяг різний у кожного бізнесу, тому ціну називаємо після брифу.",
         desc_pl="Audyt i pozycjonowanie SEO, logo i identyfikacja wizualna. Zakres zależy od firmy, dlatego cenę podajemy po briefie.",
         cta_uk="Про SEO", cta_pl="O SEO", href="svc-seo"),
  ],
  intro_title_uk="Від чого залежить ціна",
  intro_title_pl="Od czego zależy cena",
  lead_uk="Ціна сайту складається з обсягу роботи, а не з «накруток». Лендінг на одну пропозицію з формою заявки — це €300 і три дні. Сайт на двох мовах з блогом, калькулятором і оплатою — вже окремий проєкт, і ми порахуємо його чесно до старту. Фіксуємо ціну в договорі, тож доплат посеред роботи не буде, якщо не змінюється погоджений обсяг.",
  lead_pl="Cena strony wynika z zakresu pracy, a nie z „narzutów”. Landing page z jedną ofertą i formularzem to 300 € i trzy dni. Strona w dwóch językach z blogiem, kalkulatorem i płatnościami to już osobny projekt — wyceniamy go uczciwie przed startem. Cenę zapisujemy w umowie, więc w trakcie nie ma dopłat, o ile nie zmienia się uzgodniony zakres.",
  pills=[["Лендінг", "Landing page"], ["Сайт-візитка", "Strona wizytówka"], ["Корпоративний сайт", "Strona firmowa"],
         ["Інтернет-магазин", "Sklep internetowy"], ["Telegram-бот", "Bot Telegram"], ["Підтримка", "Opieka"]],
  factors=[
    ["Кількість сторінок", "Liczba podstron", "Лендінг — одна сторінка. Кожна окрема сторінка послуги, кейсу чи статті — це дизайн, верстка й тексти, тож обсяг зростає.",
     "Landing page to jedna strona. Każda podstrona usługi, realizacji czy artykułu to projekt, wdrożenie i treść, więc zakres rośnie."],
    ["Функції та інтеграції", "Funkcje i integracje", "Калькулятор, бронювання, онлайн-оплата, CRM, доставка чи Telegram-бот — усе це окремі модулі, які ми оцінюємо заздалегідь.",
     "Kalkulator, rezerwacje, płatności online, CRM, dostawa czy bot Telegram to osobne moduły, które wyceniamy z góry."],
    ["Кількість мов", "Liczba języków", "Кожна мова — окрема версія з перекладеним текстом і правильними hreflang, щоб Google показував її потрібній аудиторії.",
     "Każdy język to osobna wersja z przetłumaczoną treścią i poprawnym hreflang, żeby Google pokazywał ją właściwym odbiorcom."],
    ["Дизайн і анімації", "Design i animacje", "Акуратний сучасний дизайн є в кожному тарифі. Складні анімації, ілюстрації чи 3D-графіка потребують більше часу.",
     "Staranny, nowoczesny design jest w każdym pakiecie. Złożone animacje, ilustracje czy grafika 3D wymagają więcej czasu."],
    ["Готовність матеріалів", "Gotowość materiałów", "Якщо тексти, фото й логотип уже є, запуск швидший. Якщо ні — допоможемо зі структурою і текстами, це закладаємо в оцінку.",
     "Jeśli masz teksty, zdjęcia i logo, start jest szybszy. Jeśli nie — pomożemy ze strukturą i tekstami i uwzględnimy to w wycenie."],
  ],
  faq=[
    ["Скільки коштує сайт у 2026 році?", "Ile kosztuje strona internetowa w 2026 roku?",
     "У нас лендінг коштує від €300, багатосторінковий сайт — від €450, інтернет-магазин — від €800. Це стартові ціни для малого бізнесу. Точну суму для складнішого проєкту називаємо після короткого брифу, оцінку надсилаємо протягом 24 годин.",
     "U nas landing page kosztuje od 300 €, strona firmowa od 450 €, a sklep internetowy od 800 €. To ceny startowe dla małych firm. Dokładną kwotę za bardziej złożony projekt podajemy po krótkim briefie — wycenę wysyłamy w ciągu 24 godzin."],
    ["Чи є приховані доплати?", "Czy są ukryte dopłaty?",
     "Ні. Ціну й обсяг робіт фіксуємо в договорі до старту. Окремо оплачуються лише сторонні сервіси — домен, хостинг, платні плагіни — і нові функції, яких не було в погодженому обсязі.",
     "Nie. Cenę i zakres prac zapisujemy w umowie przed startem. Osobno płacisz tylko za usługi zewnętrzne — domenę, hosting, płatne wtyczki — oraz nowe funkcje spoza uzgodnionego zakresu."],
    ["Чи входять у ціну домен і хостинг?", "Czy domena i hosting są w cenie?",
     "Ні, домен і хостинг оплачуються окремо, напряму провайдеру, і оформлюються на вас. Ми допоможемо їх обрати й підключити — зазвичай це Hostinger або VPS, для Webflow-сайтів — Webflow hosting.",
     "Nie, domenę i hosting opłacasz osobno, bezpośrednio u dostawcy, i są zarejestrowane na Ciebie. Pomożemy je wybrać i podłączyć — zwykle to Hostinger albo VPS, a dla stron na Webflow — hosting Webflow."],
    ["Як відбувається оплата?", "Jak wygląda płatność?",
     "Офіційно, за договором і з faktura. Оплата поетапна: перший платіж перед стартом, наступний — після погодженого етапу або перед запуском. Можна платити в EUR, USD або PLN.",
     "Oficjalnie, na podstawie umowy i faktury. Płatność etapami: pierwsza wpłata przed startem, kolejna po zatwierdzonym etapie lub przed uruchomieniem. Możesz płacić w EUR, USD lub PLN."],
    ["Ціни вказані з VAT?", "Czy ceny zawierają VAT?",
     "Студія звільнена від VAT (zwolnienie z VAT), тому ціни на сайті — остаточні, без додавання податку. Faktura виставляється без VAT.",
     "Studio korzysta ze zwolnienia z VAT, więc ceny na stronie są ostateczne — nie doliczamy podatku. Faktura jest wystawiana bez VAT."],
    ["Скільки коштує підтримка сайту після запуску?", "Ile kosztuje opieka nad stroną po starcie?",
     "Перші 30 днів після запуску підтримка вже входить у тарифи «Старт» і «Про». Далі — від €20 на місяць: оновлення, невеликі правки, консультації та допомога з обслуговуванням.",
     "Przez pierwsze 30 dni po starcie wsparcie jest wliczone w pakiety Start i Pro. Później opieka kosztuje od 20 € miesięcznie: aktualizacje, drobne poprawki, konsultacje i pomoc w utrzymaniu strony."],
    ["Чому у різних студій така різна ціна?", "Dlaczego ceny w różnych agencjach tak się różnią?",
     "Бо за словом «сайт» ховаються різні обсяги: шаблон без SEO, індивідуальний дизайн чи великий проєкт з інтеграціями. Порівнюйте не суму, а що саме входить: дизайн, мобільна версія, SEO-база, аналітика, адмінка, підтримка й передача всіх доступів.",
     "Bo pod słowem „strona” kryją się różne zakresy: szablon bez SEO, indywidualny projekt albo duże wdrożenie z integracjami. Porównuj nie same kwoty, lecz to, co jest w cenie: design, wersję mobilną, podstawy SEO, analitykę, panel, wsparcie i przekazanie wszystkich dostępów."],
    ["Що потрібно, щоб отримати точну ціну?", "Co jest potrzebne do dokładnej wyceny?",
     "Короткий опис бізнесу, які сторінки й функції потрібні, мови сайту і приклади сайтів, що вам подобаються. Напишіть у Telegram або залиште заявку — відповімо протягом 24 годин у робочі дні.",
     "Krótki opis firmy, lista potrzebnych podstron i funkcji, języki strony oraz przykłady stron, które Ci się podobają. Napisz na Telegramie albo zostaw zgłoszenie — odpowiemy w ciągu 24 godzin w dni robocze."],
  ],
)

CONTACTS = dict(
  title_uk="Контакти — SHSTKV Digital, веб-студія у Вроцлаві",
  title_pl="Kontakt — SHSTKV Digital, studio stron internetowych we Wrocławiu",
  desc_uk="Зв'язатися з SHSTKV Digital: Telegram, WhatsApp, телефон +48 577 503 534, email. Відповідаємо протягом 24 годин у робочі дні. Вроцлав, Польща.",
  desc_pl="Kontakt z SHSTKV Digital: Telegram, WhatsApp, telefon +48 577 503 534, e-mail. Odpowiadamy w ciągu 24 godzin w dni robocze. Wrocław, Polska.",
  h1_uk="Контакти SHSTKV Digital",
  h1_pl="Kontakt z SHSTKV Digital",
  sub_uk="Напишіть, як вам зручно — відповімо протягом 24 годин у робочі дні.",
  sub_pl="Napisz, jak Ci wygodnie — odpowiemy w ciągu 24 godzin w dni robocze.",
  facts=[
    ["Телефон", "Telefon", "+48 577 503 534", "+48 577 503 534"],
    ["Telegram", "Telegram", "@Andrii_DEV9", "@Andrii_DEV9"],
    ["Email", "E-mail", "webdeveloperandrii@gmail.com", "webdeveloperandrii@gmail.com"],
    ["Місто", "Miasto", "Вроцлав, Польща", "Wrocław, Polska"],
    ["Години", "Godziny", "Пн–Пт", "Pon–Pt"],
  ],
  lead_uk="Найшвидше — написати в Telegram або WhatsApp. Коротко опишіть бізнес і що потрібно зробити: сайт, магазин, бот чи SEO. Якщо ще не знаєте, який формат обрати, — просто розкажіть про задачу, ми підкажемо.",
  lead_pl="Najszybciej — napisz na Telegramie lub WhatsAppie. Krótko opisz firmę i czego potrzebujesz: strony, sklepu, bota czy SEO. Jeśli nie wiesz jeszcze, jaki format wybrać — po prostu opisz zadanie, a my doradzimy.",
  sub2_uk="Працюємо з понеділка по п'ятницю. Зазвичай відповідаємо за кілька годин, максимум — за 24 години. Повідомлення ввечері чи у вихідні побачимо наступного робочого дня. Спілкуємося українською та польською. Студія у Вроцлаві, працюємо дистанційно з клієнтами по всій Польщі, в Україні та ЄС. NIP 8961659922, REGON 543289997.",
  sub2_pl="Pracujemy od poniedziałku do piątku. Zwykle odpowiadamy w kilka godzin, najpóźniej w ciągu 24 godzin. Wiadomości wysłane wieczorem lub w weekend odczytamy następnego dnia roboczego. Rozmawiamy po polsku i po ukraińsku. Studio działa we Wrocławiu, a z klientami z całej Polski, Ukrainy i UE pracujemy zdalnie. NIP 8961659922, REGON 543289997.",
  pills=[["Telegram", "Telegram"], ["WhatsApp", "WhatsApp"], ["Телефон", "Telefon"], ["Email", "E-mail"], ["Instagram", "Instagram"]],
  faq=[
    ["Що написати в першому повідомленні?", "Co napisać w pierwszej wiadomości?",
     "Чим займається бізнес, що потрібно (сайт, магазин, бот, SEO), якими мовами, і чи є вже тексти, фото та логотип. Посилання на сайти, які подобаються, дуже допомагають. Цього достатньо для першої оцінки.",
     "Czym zajmuje się firma, czego potrzebujesz (strona, sklep, bot, SEO), w jakich językach i czy masz już teksty, zdjęcia i logo. Bardzo pomagają linki do stron, które Ci się podobają. To wystarczy do pierwszej wyceny."],
    ["Чи можна зустрітися особисто?", "Czy można spotkać się osobiście?",
     "Зазвичай усе вирішуємо онлайн — дзвінком або в месенджері, це швидше для обох сторін. Якщо ви у Вроцлаві й особиста зустріч важлива, домовимося окремо.",
     "Zwykle wszystko ustalamy online — telefonicznie lub przez komunikator, tak jest szybciej dla obu stron. Jeśli jesteś we Wrocławiu i spotkanie jest ważne, umówimy się osobno."],
    ["Ви працюєте з клієнтами поза Польщею?", "Czy pracujecie z klientami spoza Polski?",
     "Так. Серед клієнтів — компанії з Польщі, України, Німеччини, Чехії, Нідерландів і США. Уся робота йде дистанційно, договір і faktura — як для польських клієнтів.",
     "Tak. Mamy klientów z Polski, Ukrainy, Niemiec, Czech, Holandii i USA. Cała współpraca odbywa się zdalnie, z umową i fakturą — tak samo jak z klientami z Polski."],
    ["Як швидко ви почнете роботу?", "Jak szybko zaczniecie pracę?",
     "Після погодження обсягу, договору й першого платежу. Лендінг запускаємо за 3–5 днів, багатосторінковий сайт — за 15–25 робочих днів, магазин — за 20–30.",
     "Po uzgodnieniu zakresu, podpisaniu umowy i pierwszej wpłacie. Landing page uruchamiamy w 3–5 dni, stronę firmową w 15–25 dni roboczych, a sklep w 20–30."],
  ],
)
